# Generated by Django 2.1.1 on 2018-09-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=127)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=127)),
                ('dependencies', models.ManyToManyField(to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.Role'),
        ),
        migrations.AddField(
            model_name='event',
            name='dependencies',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
    ]
