# Generated by Django 2.1.1 on 2019-12-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20181029_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_global',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='resources.Resource'),
        ),
    ]
