# Generated by Django 2.1.1 on 2019-12-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20191231_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_global',
        ),
        migrations.AddField(
            model_name='event',
            name='is_global',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
