# Generated by Django 2.1.1 on 2020-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['role', 'label']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['weight', 'label']},
        ),
        migrations.AddField(
            model_name='role',
            name='plural_label',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
